# dashboard_utils.py
import json
import os
import pandas as pd
from pathlib import Path

def load_reports(report_dir="reports"):
    """Load all JSON reports generated by the reviewer."""
    data = []
    report_path = Path(report_dir)
    if not report_path.exists():
        return pd.DataFrame()
    
    for file in report_path.glob("*.json"):
        try:
            with open(file, "r") as f:
                content = json.load(f)
                # Check if the report has quality score and issues
                if isinstance(content, dict) and "quality_score" in content:
                    data.append({
                        "timestamp": content.get("timestamp", str(file.stem)),
                        "file": content.get("file", ""),
                        "quality_score": content.get("quality_score", 0),
                        "issues": len(content.get("issues", []))
                    })
        except Exception as e:
            print(f"Error loading {file}: {e}")
    return pd.DataFrame(data)
